======================
7-base_geometry module
----------------------

This module contains a function that validates value.
name is a strig, value: integer greater than 0.

Import the module:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("name", 1.7)
    Traceback (most recent call last):
    TypeError: name must be an integer

    >>> bg.integer_validator("name", 7)

    >>> bg.integer_validator("name", -7)
    Traceback (most recent call last):
    ValueError: name must be greater than 0

    >>> bg.integer_validator("name", 0)
    Traceback (most recent call last):
    ValueError: name must be greater than 0

    >>> bg.integer_validator(“age”)
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg.integer_validator(“age”, {3, 4})
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg.integer_validator(“age”, True)
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg.integer_validator(“age”, [3])
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg.integer_validator(“age”, (4,))
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg.integer_validator(“age”, “4”)
    Traceback (most recent call last):
    SyntaxError: invalid character in identifier

    >>> bg = BaseGeometry()
    >>> print(dir(bg))
    ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'area', 'integer_validator']

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
